### ISSUE TITLE
URL for `--approach` in your src/README.md

### ISSUE THREAD

**Issue by letme-hj** [mmasana/FACIL#14]
It's not an issue regarding your codes,
but I just wanted to let you know that your link for more information about `--approach` seems to be something wrong. (in src/README.md)

<img width="431" alt="image" src="https://user-images.githubusercontent.com/63252804/150262360-1bd95a93-e989-4704-a3d1-f00b0088b226.png">
This leads me to [this page](https://github.com/mmasana/FACIL/blob/master/src/approaches/README.md) ,
but you must have intended to bring [this page](https://github.com/mmasana/FACIL/blob/master/src/approach/README.md) 

**(approaches -> approach)**

By the way, thank you very much for your work!! :))

**Comment by mmasana** [comment]
Fixed it, thanks!
