### ISSUE TITLE
The extensibility of the FACIL framework.

### ISSUE THREAD

**Issue by Veagau** [mmasana/FACIL#2]
Is it suitable for the more strict tasks, like the Few-shot Class Incremental Learning (FSCIL) scenario?

**Comment by mmasana** [comment]
Hi @Veagau!
I do not understand what you mean by more strict tasks. Could you clarify what you mean?
However, the framework could be adapted to do few-shot learning. I think the best way to start would be to make a copy of [src/approach/incremental_learning.py](https://github.com/mmasana/FACIL/blob/master/src/approach/incremental_learning.py) and modify the `train_loop()` and `train_epoch()` functions to those of a few-shot learning setting. If necessary, then some changes could be made to the [main_incremental.py](https://github.com/mmasana/FACIL/blob/master/src/main_incremental.py) (below line 221).
If you define a bit more the specifics of what you would like to try, I might be able to provide more insight or code.
