### ISSUE TITLE
There is a bug when running the code

### ISSUE THREAD

**Issue by zhl98** [mmasana/FACIL#25]
Traceback (most recent call last):
  File "src/main_incremental.py", line 13, in <module>
    from datasets.data_loader import get_loaders
ModuleNotFoundError: No module named 'datasets.data_loader'

**Comment by mmasana** [comment]
In the `datasets` folder there is a file called `data_loader.py`. The error seems to say as if it does not exist. Check that your paths are correct, that the file exists on that location and that you have the necessary permissions to run it.

**Comment by zhl98** [comment]
![image](https://user-images.githubusercontent.com/51871747/195790150-b3a8243e-7fc1-4823-a5c5-fe2692b86b86.png)
The  file is exist. And i also have permission to read it, 
But it's strange that he just made this mistake. And the code has not been modified since the clone came down.

**Comment by mmasana** [comment]
I just cloned a fresh version and if I do `python3 -u src/main_incremental.py` it works without this error. I'm not sure why it cannot import from that file.

Maybe you can try adding a `__init__.py` file? This could help with making sure that the path is visible to the interpreter.

**Comment by zhl98** [comment]
ok，Thank you very much. After adding a __init__.py file ,this bug  disappears.
