### ISSUE TITLE
can not reproduce the similar result as paper

### ISSUE THREAD

**Issue by wangsen1312** [mmasana/FACIL#28]
When I want to reproduce the results like figure 8 in the paper,

I run the code below:
`python3 -u src/main_incremental.py --approach ewc --num-tasks 10 --exemplar-selection herding --num-exemplars 2000
`
The results is  different from the EWC-e in the figure 8? Any tips?

**Comment by mmasana** [comment]
Which results are you getting?

We provide a mean over 10 runs with different seeds and standard deviation. Are the results within the std?

Which trade-off value are you using? For our runs, we use the Continual Hyperparameter Framework (it can be called with the `--gridsearch` argument) so we can find the most optimal trade-off value with the information at hand (no use of previous or future data).

**Comment by wangsen1312** [comment]
@mmasana Thank you for your quick response. I have tried with the gridsearch. I can almost reproduce the similar results now!
Great work!
