### ISSUE TITLE
Conversion of saved trained models (at checkpoints)

### ISSUE THREAD

**Issue by andreadaou** [mmasana/FACIL#30]
Hello,

As described in the [documentation](https://github.com/mmasana/FACIL/blob/master/src/README.md), `--save-models` allows to save the trained models after each incremental step (task). Models are saved in a `model.ckpt` format without any other additional file (.meta file, .index file).
How can I convert a saved model directly from **.ckpt** to **.pb** ?

Appreciate your help! Thank you in advance!

**Comment by mmasana** [comment]
Not sure how you can convert from one file type to another. But if you are using the `disk` logger on FACIL, then you can change the way that the models are saved by modifying this line [here](https://github.com/mmasana/FACIL/blob/master/src/loggers/disk_logger.py#L56).

**Comment by andreadaou** [comment]
Okay, thank you! I will try to make some modifications.
