### ISSUE TITLE
Unable to match the accuracy results present in the ANCL paper using FACIL framework

### ISSUE THREAD

**Issue by arnabphoenix** [mmasana/FACIL#38]
Respected Authors,
I am unable to match the results given in the paper for a-lwf,a-ewc,a-lfl.Please help me as the resulting accuracy that is coming is much less than that is being told in the paper for Tag,and Taw accuracies.Please give me some suggestions or help me.

**Comment by mmasana** [comment]
Which paper do you refer to? In our paper we do not reference any a-lwf, a-ewc or a-lfl. Could you provide more context?
