### ISSUE TITLE
HOW TO RUN THE FRAMEWORK ON IMAGENET DATASET?

### ISSUE THREAD

**Issue by arnabphoenix** [mmasana/FACIL#40]
Respected Sir,
If you could please tell me how to run the framework in imagenet dataset or any other dataset other than Cifar100,on the datasets that are mentioned here in the dataset folder.

**Comment by mmasana** [comment]
You can follow the instructions from the corresponding [README.md](https://github.com/mmasana/FACIL/blob/master/src/datasets/README.md)
