### ISSUE TITLE
Error coming while running on Imagenet Dataset

### ISSUE THREAD

**Issue by sumitra009** [mmasana/FACIL#41]
# dataset args
    parser.add_argument('--datasets', default=['imagenet_256'], type=str, choices=list(dataset_config.keys()),
                        help='Dataset or datasets used (default=%(default)s)', nargs='+', metavar="DATASET")

FileNotFoundError: ../data/ILSVRC12_256/train.txt not found.

**Comment by mmasana** [comment]
https://github.com/mmasana/FACIL/blob/master/src/datasets/README.md
